// Reference FX is fetched from Frankfurter's ECB-backed daily feed, never guessed.
let budgetPeriod='week',budgetAnchor=day(),budgetFxBusy=false,budgetFxMessage='',budgetFxLastAttempt=0;
const budgetState=()=>state.budget||{expenses:[],limits:{week:null,month:null},fx:null};
const budgetMoney=n=>Number(n).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const budgetRound=n=>Math.round((n+Number.EPSILON)*100)/100;
function budgetRange(mode,anchor){if(mode==='week'){const start=menuWeekStart(anchor);return {start,end:menuAddDays(start,6)}}const start=anchor.slice(0,7)+'-01',d=new Date(start+'T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+1);d.setUTCDate(0);return {start,end:d.toISOString().slice(0,10)}}
const budgetExpensesFor=range=>budgetState().expenses.filter(e=>e.date>=range.start&&e.date<=range.end);
const budgetSum=expenses=>({usd:budgetRound(expenses.reduce((n,e)=>n+e.usd,0)),cny:budgetRound(expenses.reduce((n,e)=>n+budgetRound(e.usd*e.fx.rate),0))});
function renderBudget(){const b=budgetState(),range=budgetRange(budgetPeriod,budgetAnchor),entries=budgetExpensesFor(range).slice().sort((a,b)=>b.date.localeCompare(a.date)),sum=budgetSum(entries),weekSum=budgetSum(budgetExpensesFor(budgetRange('week',day()))),monthSum=budgetSum(budgetExpensesFor(budgetRange('month',day())));
  const metric=(name,sums,limit)=>`<div class="budget-metric"><span class="muted">${name}</span><b>¥${budgetMoney(sums.cny)}</b><span class="muted">$${budgetMoney(sums.usd)} USD</span>${limit?`<div class="progress-track"><div class="progress-fill" style="width:${Math.min(100,sums.usd/limit*100)}%;${sums.usd>limit?'background:#ce9279':''}"></div></div><small>${sums.usd>limit?'超出':'剩余'} $${budgetMoney(Math.abs(limit-sums.usd))} / 预算 $${budgetMoney(limit)}</small>`:'<small>可在下方设置预算</small>'}</div>`;
  $('#content').innerHTML=`<div id="budget-page"><div class="section-head"><div><h2>每一笔花费，都心中有数。</h2><span class="muted">输入美元 · 换算人民币 · 查看每周和每月支出</span></div><button class="outline" id="budget-add">＋ 记一笔</button></div><div class="budget-rate"><div><b>${b.fx?'1 USD ≈ '+b.fx.rate.toLocaleString('zh-CN',{minimumFractionDigits:4,maximumFractionDigits:6})+' CNY':'正在获取 USD / CNY 汇率'}</b><span>${b.fx?'参考汇率日期 '+esc(b.fx.date)+' · ECB / Frankfurter':'尚无可用汇率，不会猜测换算结果'}</span><small role="status">${esc(budgetFxMessage)}</small></div><button class="outline" id="budget-fx-update" ${budgetFxBusy?'disabled':''}>${budgetFxBusy?'更新中…':'更新汇率'}</button></div><div class="budget-metrics">${metric('本周支出',weekSum,b.limits.week)}${metric('本月支出',monthSum,b.limits.month)}</div><div class="budget-period-controls"><div class="tabs budget-tabs"><button data-budget-mode="week" class="${budgetPeriod==='week'?'active':''}">每周</button><button data-budget-mode="month" class="${budgetPeriod==='month'?'active':''}">每月</button></div><button class="outline" data-budget-period="-1" aria-label="上一时段">‹</button><span>${range.start} — ${range.end}</span><button class="outline" data-budget-period="1" aria-label="下一时段">›</button><button class="danger" id="budget-now">当前时段</button></div><section class="chart budget-chart"><div class="section-head"><h3>人民币支出走势</h3><span class="tokens">合计 ¥${budgetMoney(sum.cny)}</span></div>${budgetChart(range,entries)}<p class="muted">$${budgetMoney(sum.usd)} USD · ${entries.length} 笔 · 人民币金额按每笔录入时的参考汇率保留</p></section><div class="history">${entries.map(e=>`<div class="entry budget-entry"><div>${esc(e.name)}<small>${esc(e.date)} · ${esc(e.category)} · 汇率日期 ${esc(e.fx.date)}</small></div><div class="budget-entry-amount"><b>¥${budgetMoney(budgetRound(e.usd*e.fx.rate))}</b><small>$${budgetMoney(e.usd)}</small><button class="danger" data-budget-delete="${esc(e.id)}">删除</button></div></div>`).join('')||'<div class="empty">所选时段还没有支出。记一笔，看看钱花在哪里。</div>'}</div><section class="card budget-limits"><h3>给花费设一个边界</h3><form id="budget-limits-form"><div><label for="budget-week-limit">每周预算（USD，可留空）</label><input id="budget-week-limit" type="number" step="0.01" min="0.01" max="10000000" value="${b.limits.week||''}"></div><div><label for="budget-month-limit">每月预算（USD，可留空）</label><input id="budget-month-limit" type="number" step="0.01" min="0.01" max="10000000" value="${b.limits.month||''}"></div><button class="outline">保存预算</button></form></section><p class="muted">参考汇率通常在工作日更新，不是银行实时成交价；手续费和刷卡实际汇率可能不同。</p></div>`;
  $('#budget-add').onclick=openBudgetExpense;$('#budget-fx-update').onclick=()=>updateBudgetRate(true);$('#budget-page').onclick=handleBudgetClick;
  $('#budget-limits-form').onsubmit=e=>{e.preventDefault();const limits=Object.fromEntries(['week','month'].map(k=>{const v=$('#budget-'+k+'-limit').value;return [k,v?budgetRound(Number(v)):null]}));const next={...budgetState(),limits};if(!validBudget(next)){toast('请填写有效的美元预算');return}if(commit({...state,budget:next}))toast('预算已保存')};
  const last=b.fx?Date.parse(b.fx.fetchedAt):0;if(!budgetFxBusy&&Date.now()-last>86400000&&Date.now()-budgetFxLastAttempt>300000)updateBudgetRate(false);
}
async function updateBudgetRate(force){if(budgetFxBusy)return;budgetFxBusy=true;budgetFxLastAttempt=Date.now();budgetFxMessage='正在查询最新参考汇率…';if(tab==='budget')renderBudget();
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);
  try{const response=await fetch('https://api.frankfurter.dev/v1/latest?base=USD&symbols=CNY',{signal:controller.signal,cache:'no-store'});if(!response.ok)throw Error('汇率服务暂时不可用');const result=await response.json(),fx={rate:Number(result.rates?.CNY),date:result.date,fetchedAt:new Date().toISOString()};if(result.base!=='USD'||!validBudgetRate(fx))throw Error('汇率数据格式异常');budgetFxMessage='已取得最新可获取的参考汇率';const next={...budgetState(),fx};if(!commit({...state,budget:next}))budgetFxMessage='汇率已查询，但未能保存，请重试';if($('#budget-expense-editor').open)updateBudgetPreview();}
  catch(error){budgetFxMessage=budgetState().fx?'更新失败，暂用 '+budgetState().fx.date+' 的已保存汇率。可点击更新重试。':'未能获取汇率，请检查网络后点击更新；目前无法保存换算支出。';}
  finally{clearTimeout(timer);budgetFxBusy=false;if(tab==='budget')renderBudget()}
}
function handleBudgetClick(event){const button=event.target.closest('button');if(!button)return;const d=button.dataset;
  if(d.budgetMode){budgetPeriod=d.budgetMode;renderBudget();return}
  if(d.budgetPeriod){const n=Number(d.budgetPeriod);if(budgetPeriod==='week')budgetAnchor=menuAddDays(budgetAnchor,n*7);else{const date=new Date(budgetAnchor.slice(0,7)+'-01T12:00:00Z');date.setUTCMonth(date.getUTCMonth()+n);budgetAnchor=date.toISOString().slice(0,10)}renderBudget();return}
  if(button.id==='budget-now'){budgetAnchor=day();renderBudget();return}
  if(d.budgetDelete&&confirm('删除这笔支出？')){const b=budgetState();commit({...state,budget:{...b,expenses:b.expenses.filter(e=>e.id!==d.budgetDelete)}})}
}
function budgetChart(range,expenses){const count=Math.round((Date.parse(range.end)-Date.parse(range.start))/86400000)+1,bars=Array.from({length:count},(_,i)=>{const date=menuAddDays(range.start,i);return {date,value:budgetSum(expenses.filter(e=>e.date===date)).cny}});const width=700,height=220,left=58,right=15,top=24,bottom=38,max=Math.max(1,...bars.map(b=>b.value)),space=(width-left-right)/count;
  let svg=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${range.start}至${range.end}的每日人民币支出，总额${budgetMoney(budgetSum(expenses).cny)}元">`;
  for(let i=0;i<4;i++){const value=max*i/3,y=height-bottom-value/max*(height-top-bottom);svg+=`<line x1="${left}" x2="${width-right}" y1="${y}" y2="${y}" stroke="#eee8f4"/><text x="3" y="${y+4}" fill="#9686a2" font-size="11">${value.toFixed(0)}</text>`}
  bars.forEach((b,i)=>{const h=b.value/max*(height-top-bottom),x=left+i*space+space*.2;svg+=`<rect x="${x}" y="${height-bottom-h}" width="${space*.6}" height="${h}" rx="3" fill="#ad8bd6"><title>${b.date}：¥${budgetMoney(b.value)}</title></rect>`;if(count<=7||i%5===0||i===count-1)svg+=`<text x="${x+space*.3}" y="${height-10}" text-anchor="middle" fill="#9686a2" font-size="11">${b.date.slice(5)}</text>`});return svg+'</svg>';
}
const budgetDialog=document.createElement('dialog');budgetDialog.id='budget-expense-editor';budgetDialog.innerHTML=`<form id="budget-expense-form"><h2>记一笔支出</h2><label for="budget-name">买了什么？</label><input id="budget-name" maxlength="120" required placeholder="例如：午餐 / 书 / 咖啡"><label for="budget-category">类别</label><select id="budget-category">${['餐饮','购物','交通','学习','娱乐','其他'].map(x=>`<option>${x}</option>`).join('')}</select><label for="budget-date">日期</label><input id="budget-date" type="date" required><label for="budget-usd">美元金额（USD）</label><input id="budget-usd" type="number" min="0.01" max="10000000" step="0.01" required placeholder="0.00"><p id="budget-preview" class="budget-preview" role="status">输入美元金额，查看人民币换算</p><div class="actions"><button class="outline" type="button" id="budget-expense-cancel">取消</button><button class="primary" id="budget-expense-save">保存支出</button></div></form>`;document.body.appendChild(budgetDialog);
function openBudgetExpense(){$('#budget-expense-form').reset();$('#budget-date').value=day();updateBudgetPreview();budgetDialog.showModal();$('#budget-name').focus()}
function updateBudgetPreview(){const fx=budgetState().fx,usd=Number($('#budget-usd').value);$('#budget-preview').textContent=fx?'约 ¥'+budgetMoney(budgetRound(usd*fx.rate))+' CNY · 参考汇率日期 '+fx.date:'尚未获取汇率，请关闭后更新汇率再记账';$('#budget-expense-save').disabled=!fx;}
$('#budget-usd').oninput=updateBudgetPreview;$('#budget-expense-cancel').onclick=()=>budgetDialog.close();
$('#budget-expense-form').onsubmit=e=>{e.preventDefault();const b=budgetState(),expense={id:crypto.randomUUID(),name:$('#budget-name').value.trim(),category:$('#budget-category').value,date:$('#budget-date').value,usd:budgetRound(Number($('#budget-usd').value)),fx:b.fx?{...b.fx}:null};const next={...b,expenses:[...b.expenses,expense]};if(!validBudget(next)){toast('请填写有效记录并先获取汇率');return}if(commit({...state,budget:next})){budgetDialog.close();toast('支出已保存，人民币金额保留当前换算结果')}};
